/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewwindowdriver;

import java.awt.Frame;

/**
 *
 * @author Sean
 */
public class AddUserDialog extends javax.swing.JDialog {
    Frame frame;
    /**
     * Creates new form AddUserDialog
     */
    public AddUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.frame = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newFirstNameBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        newLastNameBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        newUserNameBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passwordBox1 = new javax.swing.JPasswordField();
        passwordBox2 = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add User");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 0, -1, -1));

        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 29, -1, -1));

        newFirstNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFirstNameBoxActionPerformed(evt);
            }
        });
        getContentPane().add(newFirstNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));
        getContentPane().add(newLastNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, -1));

        jLabel4.setText("UserName");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        getContentPane().add(newUserNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 100, -1));

        jLabel5.setText("Re-Enter Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        getContentPane().add(passwordBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, -1));
        getContentPane().add(passwordBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, -1));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        addUserButton.setText("AddUser");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFirstNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFirstNameBoxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_newFirstNameBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
        User user = new User();
        user.setFirstName(newFirstNameBox.getText());
        
        user.setLastName(newLastNameBox.getText());
        user.setUserName(newUserNameBox.getText());
        String pass1 = new String(passwordBox1.getPassword());
        String pass2 = new String(passwordBox2.getPassword());
        UserDB userDB = new UserDB("jdbc:sqlite:timemanager.db");
        if (pass1.compareTo(pass2) == 0) {
            
            user.setPassword(pass2);
            userDB.setData(user);
            
            InfoDialog diag = new InfoDialog(frame, true, "User Added");
            diag.setLocationRelativeTo(frame);
            diag.setVisible(true);
            dispose();
            
        }
        else {
            InfoDialog diag = new InfoDialog(frame, true, "Passwords Do Not Match!");
            diag.setLocationRelativeTo(frame);
            diag.setVisible(true);
            //System.out.println("Passwords do not match");
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddUserDialog dialog = new AddUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    } */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField newFirstNameBox;
    private javax.swing.JTextField newLastNameBox;
    private javax.swing.JTextField newUserNameBox;
    private javax.swing.JPasswordField passwordBox1;
    private javax.swing.JPasswordField passwordBox2;
    // End of variables declaration//GEN-END:variables
}
